<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO7GYSCP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO7GYSCP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO7GYSCP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO7GYSCP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerO7GYSCP\App_KernelDevDebugContainer([
    'container.build_hash' => 'O7GYSCP',
    'container.build_id' => '7f0239f9',
    'container.build_time' => 1677836904,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO7GYSCP');
